version = 1

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "17"

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "test-coverage"